app:
  historyItemsMax = 10

integration:
  # Open exchange rates configuration https://openexchangerates.org
  oxr:
    appId:
    api: https://openexchangerates.org/api
    latestApi: ${integration.oxr.api}/latest.json?app_id={app_id}&base={base}&symbols={symbols}
    historicalApi: ${integration.oxr.api}/historical/{exchangeRateDate}.json?app_id={app_id}&base={base}&symbols={symbols}

spring:
  jackson:
    serialization.write_dates_as_timestamps: false
  jpa:
    open-in-view: false
    show-sql: false
    properties:
      hibernate.format_sql: false

management:
  contextPath: /actuator
  security:
    enabled: false

security:
  basic:
    enabled: false

logging:
  level:
    com.zooplus.sdc.converter: INFO
    org.springframework.web: DEBUG

---
spring:
    profiles: dev
server:
    port: 8081